name: rustenburg
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.5+5

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_signature_pad: ^3.0.0
  shared_preferences: ^2.0.7
  http: ^0.13.3
  fluttertoast: ^8.0.8
  intl: ^0.16.0
  dio: ^4.0.0
  path_provider: ^2.0.2
  image_gallery_saver: ^1.6.9
  flutter_slidable: ^0.6.0
#  file_picker: ^3.0.2+2
#  file_picker: ^4.3.3
  file_picker: ^4.5.0
  mask_text_input_formatter: ^2.0.0
  flutter_cupertino_datetime_picker: ^2.0.1
#  barcode_scan2: ^4.1.3
  barcode_scan2: ^4.2.1
  # barcode_scan: ^3.0.1
  camera_camera: ^2.0.2
  image_picker: ^0.8.0+3
#  image_picker: ^0.7.4
  cached_network_image: ^3.0.0
  mime: ^1.0.0
  hexcolor: ^2.0.4
  barcode_keyboard_listener: ^0.0.1
  flutter_masked_text: ^0.8.0
  location: ^4.2.3
  permission_handler: ^8.0.1
  ext_storage: ^1.0.3

  # access app cache files
  flutter_cache_manager: ^3.1.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

dependency_overrides:
  file_picker: ^1.5.0+1
  flutter_plugin_android_lifecycle: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
#  image_path: "assets/images/ramotshere.JPG"
  image_path: "assets/images/launcher_icon_rustenburg.jpg"
#  image_path: "assets/images/m_launcher_icon.jpg"
#  image_path: "assets/images/lesedi_app_icon.jpg"
  #  image_path_android: "assets/images/app-icon.png"
  #  image_path_ios: "assets/images/icon-710x599-ios.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
#  adaptive_icon  _background: "assets/images/app-icon.png" # only available for Android 8.0 devices and above
#  adaptive_icon_foreground: "assets/images/app-icon.png" # only available for Android 8.0 devices and above


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: .AppleSystemUIFont
      fonts:
        - asset: assets/fonts/SFNS.ttf
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
